import Peperroni from "../assets/Peperroni-Pizza.png";
import Meatpizza from "../assets/meat-pizza.png";
import Hpizza from "../assets/hawaiian-pizza.png";
import MargheritaPizza from "../assets/Margherita-pizza.png";
import SupremePizza from "../assets/supreme-pizza3.png";
import GrilledPizza from "../assets/grilled-veg-pizza.png";
import TandooriChicken from "../assets/tandoori-chicken-pizza3.png";
import Country from "../assets/country-burger.png";
import DoubleCheese from "../assets/double-cheese.png";
import Vegan from "../assets/vegan-burger2.png";
import ClassicVeg from "../assets/classic-veg-burger.png";
import PaneerVeg from "../assets/spicy-panner-burger.png";
import DoubleDecker from "../assets/double_decker.png";
import VegDouble from "../assets/veg-decker2.png";
import ChickenPot from "../assets/chicken-one-pot.png";
import GrilledChicken from "../assets/grilled-chicken.webp";
import GrilledChicken2 from "../assets/grilled-chicken2.webp";
import VeganChicken from "../assets/vegan-chicken2.png";
import ChickenNoodleSoup from "../assets/chicken-noodle-soup.png";
import Crinklecut from "../assets/crinkle-cut-fries2.png";
import Curlycut from "../assets/curly-fries.png";
import Fries from "../assets/fries.jpg";
import SpecialFries from "../assets/special-fries2.png";

export const dishes = [
  {
    id: "menu__peperroni",
    dishName: "Peperroni Pizza",
    image: Peperroni,
    price: 180,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "pizza",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__meat",
    dishName: "Meat Pizza",
    image: Meatpizza,
    price: 230,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "pizza",
    isVeg: false,
    special: false,
  },
  {
    id: "menu__hawaiian",
    dishName: "Hawaiian Pizza",
    image: Hpizza,
    price: 260,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "pizza",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__margherita",
    dishName: "Margherita Pizza",
    image: MargheritaPizza,
    price: 230,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "pizza",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__supreme",
    dishName: "Supreme Pizza",
    image: SupremePizza,
    price: 280,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "pizza",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__grilled",
    dishName: "Grilled Pizza",
    image: GrilledPizza,
    price: 230,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "pizza",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__tandoori-chicken",
    dishName: "Tandoori Chicken Pizza",
    image: TandooriChicken,
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "pizza",
    isVeg: false,
    special: false,
  },
  {
    id: "menu__country",
    dishName: "Country Burger",
    image: Country,
    price: 80,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "burger",
    isVeg: false,
    special: false,
  },
  {
    id: "menu__double-cheese",
    dishName: "Double Cheese Burger",
    image: DoubleCheese,
    price: 80,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "burger",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__tofu",
    dishName: "Vegan Tofu Burger",
    image: Vegan,
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "burger",
    isVeg: true,
    special: true,
  },
  {
    id: "menu__classic-veg",
    dishName: "Classic Veg Burger",
    image: ClassicVeg,
    price: 70,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "burger",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__spicy-paneer",
    dishName: "Spicy Paneer Burger",
    image: PaneerVeg,
    price: 110,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "burger",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__double-decker",
    dishName: "Double Decker",
    image: DoubleDecker,
    price: 239,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "burger",
    isVeg: false,
    special: false,
  },
  {
    id: "menu__veg-double-decker",
    dishName: "Veg Double Decker",
    image: VegDouble,
    price: 222,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "burger",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__chicken",
    dishName: "Chicken one pot",
    image: ChickenPot,
    price: 340,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "chicken",
    isVeg: false,
    special: false,
  },
  {
    id: "menu__grilled-chicken",
    dishName: "Grilled Chicken (Sp.)",
    image: GrilledChicken,
    price: 420,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "chicken",
    isVeg: false,
    special: false,
  },
  {
    id: "menu__coconut-rice",
    dishName: "Grilled Chicken with Rice",
    image: GrilledChicken2,
    price: 420,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "chicken",
    isVeg: false,
    special: false,
  },
  {
    id: "menu__vegan-chicken",
    dishName: "Vegan Chicken",
    image: VeganChicken,
    price: 480,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "chicken",
    isVeg: true,
    special: true,
  },
  {
    id: "menu__chicken-noodle",
    dishName: "Chicken Noodle Soup",
    image: ChickenNoodleSoup,
    price: 230,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "chicken",
    isVeg: false,
    special: false,
  },
  {
    id: "menu__crinkle",
    dishName: "Crinkle cut fries",
    image: Crinklecut,
    price: 160,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "fries",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__curly",
    dishName: "Curly cut fries",
    image: Curlycut,
    price: 170,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "fries",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__regular",
    dishName: "Regular Fries",
    image: Fries,
    price: 80,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "fries",
    isVeg: true,
    special: false,
  },
  {
    id: "menu__special",
    dishName: "Our Special Fries",
    image: SpecialFries,
    price: 220,
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, tempore laboriosam praesentium inventore et amet tenetur necessitatibus culpa voluptates debitis.",
    category: "fries",
    isVeg: true,
    special: true,
  },
];
